openapi: 3.0.0
info:
  title: Choreo Service Sample API
  description: API specification for the Choreo Service Sample
  version: 1.0.0
servers:
  url: http://localhost:8080
paths:
  /test:
    get:
      summary: Test endpoint
      description: Returns a simple JSON message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
